# Generated by Django 4.0.1 on 2022-03-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('contact', models.IntegerField(max_length=12)),
                ('booking_date', models.TextField()),
                ('booking_place', models.DateField()),
                ('adult', models.TextField(max_length=10)),
                ('children', models.TextField(max_length=10)),
            ],
        ),
    ]
